#cloud-config
apt_upgrade: true
apt_update: true
apt_reboot_if_required: true

packages:
 - curl
 - python3-pip

runcmd:
  - export PATH=$PATH:/usr/local/bin
  - pip install --upgrade pip
  - pip install awscli --ignore-installed six
  - hostId=$(curl --silent http://169.254.169.254/latest/meta-data/instance-id)
  - hostRegion=$(curl --silent http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
  - hostRole=$(aws --region ${hostRegion} ec2 describe-tags --filters "Name=resource-id,Values=$hostId" "Name=key,Values=Role" --output=text | cut -f5)
  - hostn=$(curl --silent http://169.254.169.254/latest/meta-data/hostname | sed "s/^ip-/${hostRole}-/")
  - echo "Set hostname to $hostn"
  - echo $hostn > /etc/hostname
  - aws --region ${hostRegion} ec2 create-tags --resources ${hostId} --tags Key=Name,Value=${hostn}
power_state:
  mode: reboot
