#cloud-config
repo_update: true
repo_upgrade: all

packages:
 - epel-release
 - curl
 - python-pip

runcmd:
  - export PATH=$PATH:/usr/local/bin
  - pip install --upgrade pip
  - pip install awscli --ignore-installed six
  - [easy_install, "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz"]
  - [curl, -O, "https://raw.githubusercontent.com/aws-quickstart/quickstart-linux-bastion/master/scripts/bastion_bootstrap.sh"]
  - /bin/bash bastion_bootstrap.sh -- --tcp-forwarding true --enable false
