#cloud-config
repo_update: true
repo_upgrade: all

packages:
 - epel-release
 - curl
 - python-pip

# - name: sethostname.service
#   command: start
#   content: |
#     [Unit]
#     Description=Set Hostname Workaround https://github.com/coreos/bugs/issues/1272

#     [Service]
#     Type=oneshot
#     ExecStart=/bin/sh -c "/usr/bin/hostnamectl set-hostname $(curl -s http://169.254.169.254/latest/meta-data/hostname | sed 's/^ip-/bastion-/')"

#     [Install]
#     WantedBy=local.target

runcmd:
  - hostn=$(cat curl -s http://169.254.169.254/latest/meta-data/hostname | sed 's/^ip-/bastion-/')
  - echo "Set hostname to $hostn"
  - echo $hostn > /etc/hostname
  - export PATH=$PATH:/usr/local/bin
  - pip install --upgrade pip
  - pip install awscli --ignore-installed six
  - [easy_install, "https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz"]
  - [curl, -O, "https://raw.githubusercontent.com/aws-quickstart/quickstart-linux-bastion/master/scripts/bastion_bootstrap.sh"]
  - /bin/bash bastion_bootstrap.sh -- --tcp-forwarding true --enable false
